apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  SPRING_DATA_MONGODB_USERNAME: admin
  SPRING_DATA_MONGODB_PASSWORD: password
  TOKEN_MERCADO_PAGO: TEST-2986934127013785-042221-fd19beb63eb9225c3ae626d6800cb09a-166893008
  PUBLIC_KEY_MERCADO_PAGO: TEST-80f753c3-e00a-4a82-9980-f138127d7bef