package com.tech_challenge_fiap.data.models;

import com.tech_challenge_fiap.entities.order.OrderEntityStatusEnum;
import lombok.*;
import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.time.LocalDateTime;
import java.util.List;

@DynamoDBTable(tableName = "tech-challenge-orders") 
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OrderDataModel {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    @NonNull
    private OrderEntityStatusEnum status;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedJson
    private ClientDataModel client;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedJson 
    @NonNull
    private List<ProductDataModel> products;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedJson
    @NonNull
    private PaymentDataModel payment;

    @DynamoDBRangeKey
    @DynamoDBAttribute(attributeName = "createdAt")
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    @NonNull
    private LocalDateTime createdAt;
    

    public static class LocalDateTimeConverter implements DynamoDBTypeConverter<String, LocalDateTime> {
        @Override
        public String convert(LocalDateTime dateTime) {
            return dateTime.toString();
        }
        
        @Override
        public LocalDateTime unconvert(String string) {
            return LocalDateTime.parse(string);
        }
    }
}
