package com.tech_challenge_fiap.data.models;

import com.tech_challenge_fiap.utils.enums.PaymentStatusEnumEntity;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

@Getter
@Setter
@DynamoDBTable(tableName = "tech-challenge-payments")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentDataModel {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    String id;

    @DynamoDBAttribute
    String qrImage;

    @DynamoDBAttribute
    String qrCode;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    PaymentStatusEnumEntity status;
}
