package com.tech_challenge_fiap.data.models;

import com.tech_challenge_fiap.utils.enums.CategoryEnum;
import lombok.*;
import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "tech-challenge-products")
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class ProductDataModel {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBRangeKey  
    @DynamoDBAttribute(attributeName = "category")
    @DynamoDBTypeConvertedEnum
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "ByCategory")  
    private CategoryEnum category;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "ByName")
    private String name;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private String image;

    @DynamoDBAttribute
    @DynamoDBIndexRangeKey(globalSecondaryIndexNames = {"ByCategory", "ByPromotion"})
    private Long price;

    @DynamoDBAttribute
    private Long priceForClient;

    @DynamoDBAttribute
    private Long quantity;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "ByPromotion")
    private String hasPromotion;

    public void setPromotion(boolean isPromotion) {
        this.hasPromotion = isPromotion ? "true" : "false";
    }

    public boolean isPromotion() {
        return "true".equals(this.hasPromotion);
    }
}
